--BUSCA NA TABELA FULL
SELECT * FROM CUSTOMER;

--BUSCA NA TABELA TRAZENDO CAMPOS DESEJADOS
SELECT 
	PRODUCT_ID,
	DESCRIPTION,
	PRICE
FROM PRODUCT;



-- BUSCA NA TABELA MODIFICANDO VALORES E USANDO ALIAS PARA RENOMEAR UMA TABELA
SELECT 
	PRODUCT_ID,
	DESCRIPTION,
	PRICE,
	PRICE * 1.07 AS TAXED_PRICE
FROM PRODUCT;

-- BUSCA NA TABELA MODIFICANDO VALORES, USANDO ALIAS PARA RENOMEAR UMA TABELA E
-- USANDO ROUND PARA ARREDONDAR UM VALOR EM 1 CASA DECIMAL NO MÁXIMO
 SELECT 
	PRODUCT_ID,
	DESCRIPTION,
	PRICE,
	round(PRICE * 1.07, 1) AS TAXED_PRICE
FROM PRODUCT;

-- INTERPOLAÇÃO DE TEXTO
SELECT NAME,
	CITY || ', ' || STATE AS LOCATION
FROM CUSTOMER;

-- INTERPOLAÇÃO DE TEXTO
SELECT NAME,
	STREET_ADDRESS ||  ', ' || CITY || ', ' || STATE || ' ' || ZIP AS SHIT_ADDRESS
FROM CUSTOMER;

